import java.util.Scanner;

public class Menu {


       private int choice;
       private boolean repeat = true;



      public Menu(){

          while(repeat)
          {
              this.menuChoices();
              this.lineBreak();
              this.optionChoice();
              this.lineBreak();
          }

      }

      public void menuChoices(){

          Scanner kboard = new Scanner(System.in);
          System.out.println("\nMenu");
          System.out.println("\n1: Explain game rules");
          System.out.println("\n2: Play game");
          System.out.println("\n3: Exit");
          this.choice=kboard.nextInt();

      }

      public void optionChoice(){

          switch (choice){

              case 1:

                  ExplainRules bullsAndCows = new ExplainRules("The game will generate a 4 digit number generated by adding 4 numbers from 1-9 together that the user will guess." +
                          "\nA score of bull will be given for every digit guessed in the correct location" +
                          "\nA score of cow will be given to each correct number guessed\n", "Bulls and Cows");

                  bullsAndCows.showRules();

                  break;

              case 2:

                  BullAndCowGame G1 = new BullAndCowGame();


                  break;

              case 3:

                  System.out.println("\nNow exiting...... goodbye! :)\n");
                  repeat=false;

                  break;
          }

      }

      public void lineBreak(){

          System.out.println("-------------------------------------------------------------");

      }




}
